version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb12
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: test
            MONGO_INITDB_ROOT_PASSWORD: test
            MONGO_INITDB_DATABASE: test
        ports:
            - 27018:27017

            